title: CSC Learning Materials
description: Official training documentation for CSC staff and partners.
theme: just-the-docs

logo: "CSC_logo.svg"
logo_link: "https://csc.fi/en/"
color_scheme: CSC-colours

# Navigation & Search
heading_anchors: true      # Makes it easy for people to link to specific sections
aux_links:
  "CSC Website": "https://csc.fi"

# Points to the correct fork automatically!
gh_edit_repository: "https://github.com/{{ site.github.repository_nwo }}"
gh_edit_view_mode: "tree"
gh_edit_branch: "main"

search_enabled: false
footer_content: "© 2026 CSC – IT Center for Science"